name: Build and push images

on:
  push:
    branches:
      - main
    paths:
      - images/**
      - .github/**

  pull_request:
    branches:
      - main
    paths:
      - images/**
      - .github/**

env:
  REGISTRY: ghcr.io

jobs:
  changed:
    name: Detect changed images
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Get changed files
        id: changed
        uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 # v47.0.1
        with:
          files: images/**
          dir_names: true
          dir_names_max_depth: 2

      - name: Set matrix
        id: set-matrix
        run: |
          # Extract unique image directories
          IMAGES=$(echo '${{ steps.changed.outputs.all_changed_files }}' | tr ' ' '\n' | grep '^images/' | cut -d'/' -f2 | sort -u | jq -R . | jq -s -c '.')
          echo "matrix={\"image\":$IMAGES}" >> $GITHUB_OUTPUT
          echo "Images to build: $IMAGES"

  build:
    name: Build ${{ matrix.image }}
    needs: changed
    if: ${{ fromJSON(needs.changed.outputs.matrix).image[0] != null }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix: ${{ fromJSON(needs.changed.outputs.matrix) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Extract version from Dockerfile
        id: version
        run: |
          VERSION=$(grep -m1 '^ARG.*VERSION=' images/${{ matrix.image }}/Dockerfile | cut -d'=' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version for ${{ matrix.image }}: $VERSION"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - name: Log into ghcr.io
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: images/${{ matrix.image }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/smauermann/${{ matrix.image }}:${{ steps.version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

